[env]
MISE_ENV_FILE = ".env"
LOGLEVEL = "info"
GIT_AUTHOR_EMAIL = "nikhil@theori.io"

[settings.python]
uv_venv_auto = true

[tools]
uv = "latest"
rust = "latest"
go = "latest"
node = "22"
terraform = "1"
pnpm = "latest"
gcloud = "latest"
"npm:@openai/codex" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
